version: 2.1

orbs:
  haskell: haskell-works/haskell-build@1.6.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build:
          name: GHC 8.2.2
          executor: haskell/ghc-8_2_2
          working_directory: ~/project/haskell-build/projects/v110-a
