version: 2.1

description: |
  Manages GitHub releases
  Repository: https://github.com/haskell-works/hw-circle-orbs

executors:
  default:
    docker:
      - image: circleci/buildpack-deps:latest

common-params: &common-params
  github-token:
    description: Either enter GitHub token here or set GITHUB_TOKEN env variable.
    type: string
    default: ${GITHUB_TOKEN}
  before-release:
    description: |
      Optional steps to run before making a release.
      This is normally used for preparing artefacts to upload to the release.
    type: steps
    default: []
  after-release:
    description: |
      Optional steps to run after the release is made.
      Use it for cleanup resources, persisting workspaces if needed, etc.
    type: steps
    default: []
  artefacts-folder:
    description: |
      File path to be uploaded.
      If directory, all files in the directory will be uploaded.
      If empty, just create a new release without uploading any files.
    type: string
    default: "/tmp/artefacts"
  draft:
    description: Set true if the release is a draft.
    type: boolean
    default: false
  pre-release:
    description: Set true if the release is a pre-release.
    type: boolean
    default: false
  aws-access-key-id:
    description: AWS Access Key Id for uploading artefacts to S3 bucket
    type: string
    default: ${AWS_ACCESS_KEY_ID}
  aws-secret-access-key:
    description: AWS Secret Access Id for uploading artefacts to S3 bucket
    type: string
    default: ${AWS_SECRET_ACCESS_KEY}
  artefacts-bucket:
    description: The artefacts bucket to upload artefacts to
    type: string
    default: ${ARTEFACTS_BUCLET}

commands:
  release-cabal:
    description: Creates a new release using a version from .cabal file
    parameters:
      <<: *common-params
      cabal-file:
        description: Cabal file name (including the .cabal extension)
        type: string
        default: ""
    steps:
      - when:
          condition: << parameters.cabal-file >>
          steps:
            - run:
                name: "Validating provided cabal file"
                command: |
                  if [ ! -f "<< parameters.cabal-file >>" ]; then
                    echo "Cabal file was specified, but doesn't exist << parameters.cabal-file >>"
                    exit 1
                  fi
                  BUILD_CABAL_FILE=<< parameters.cabal-file >>
                  echo "export BUILD_CABAL_FILE=$BUILD_CABAL_FILE" >> $BASH_ENV
                  source $BASH_ENV
      - unless:
          condition: << parameters.cabal-file >>
          steps:
            - run:
                name: Searching for Cabal file to build
                command: |
                  BUILD_CABAL_FILE=$((ls ${CIRCLE_PROJECT_REPONAME}.cabal || ls *.cabal) | head -n 1)
                  ## What to do with multiple cabal packages?
                  # BUILD_CABAL_FILE=$((ls ${CIRCLE_PROJECT_REPONAME}.cabal || ls *.cabal || find . -type f -name '*.cabal') | head -n 1)
                  if [ "$BUILD_CABAL_FILE" = "" ]; then
                    echo "Could not find .cabal file"
                    exit 1
                  fi
                  echo "Found $BUILD_CABAL_FILE, using it"
                  echo "export BUILD_CABAL_FILE=$BUILD_CABAL_FILE" >> $BASH_ENV
                  source $BASH_ENV
      - run:
          name: Reading version from cabal file
          command: |
            TAG_VERSION=$(cat $BUILD_CABAL_FILE | grep -e "^version" | head -n 1 | tr -s ' ' | cut -d' ' -f2)
            echo "Current version is $TAG_VERSION"
            echo "TAG_VERSION=$TAG_VERSION" >> $BASH_ENV
            source $BASH_ENV
      - release:
          github-token: << parameters.github-token >>
          tag: v$TAG_VERSION
          title: Release v$TAG_VERSION
          before-release: << parameters.before-release >>
          after-release: << parameters.after-release >>
          artefacts-folder: << parameters.artefacts-folder >>
          draft: << parameters.draft >>
          pre-release: << parameters.pre-release >>

  release:
    description: Create a new release.
    parameters:
      <<: *common-params
      tag:
        description: Git tag using as the version number of the release.
        type: string
      title:
        description: Name of the release.
        type: string
    steps:
      - setup-ghr
      - check-tag-exists:
          tag: << parameters.tag >>

      - produce-change-log:
          github-token: << parameters.github-token >>
          artefacts-folder: << parameters.artefacts-folder >>

      - when:
          condition: << parameters.before-release >>
          steps: << parameters.before-release >>

      - run:
          name: "Publishing a new release with artefacts"
          command: |
              changes=`cat << parameters.artefacts-folder >>/changelog.txt`
              ghr \
                --token << parameters.github-token >> \
                --username ${CIRCLE_PROJECT_USERNAME} \
                --repository ${CIRCLE_PROJECT_REPONAME} \
                --commitish ${CIRCLE_SHA1} \
                --name "<< parameters.title >>" \
                --body "$changes" \
                --soft \
                <<# parameters.draft >> --draft <</ parameters.draft >> \
                <<# parameters.pre-release >> --prerelease <</ parameters.pre-release >> \
                  << parameters.tag >> << parameters.artefacts-folder >>
              echo "Published version: << parameters.tag >>"

      - when:
          condition: << parameters.after-release >>
          steps: << parameters.after-release >>

  check-tag-exists:
    description: Checks if the current tag exists. Sets RELEASE_EXISTS env variable if so.
    parameters:
      tag:
        description: Git tag using as the version number of the release.
        type: string
    steps:
      - run:
          name: Check if release exists
          command: |
            if [[ $(git ls-remote origin "refs/tags/<< parameters.tag >>") ]]; then
              echo "The tag << parameters.tag >> already exists."
              echo "export RELEASE_EXISTS=true" >> $BASH_ENV
              source $BASH_ENV
            fi

  produce-change-log:
    description: Produces change log - a list of commits since last release
    parameters:
      github-token:
        description: Either enter GitHub token here or set GITHUB_TOKEN env variable.
        type: string
        default: ${GITHUB_TOKEN}
      artefacts-folder:
        description: |
          File path to be uploaded.
          If directory, all files in the directory will be uploaded.
          If empty, just create a new release without uploading any files.
        type: string
    steps:
      - run:
          name: Producing change log
          command: |
            mkdir -p << parameters.artefacts-folder >>
            _changelog_file="<< parameters.artefacts-folder >>/changelog.txt"
            echo $'Changes\n--------\n' > ${_changelog_file}
            _api_auth="Authorization: token << parameters.github-token >>"
            _api_url="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
            _latest_release=$(curl -s -H "${_api_auth}" -X GET ${_api_url}/releases/latest | jq -r '.tag_name // ""')
            if [ "$_latest_release" = "" ]; then _latest_release=${CIRCLE_SHA1}; fi
            curl -s -H "${_api_auth}" \
              -X GET ${_api_url}/compare/${_latest_release}...${CIRCLE_SHA1} \
              | jq -cr '.commits[] | "- \(.commit.message) by @\(.author.login)" | gsub("[\n]"; " ")' \
              >> ${_changelog_file}

  setup-ghr:
    description: "Downloads GHR tool and puts it to /usr/local/bin"
    steps:
      - run:
          name: Download GitHub Releases tool
          command: |
            curl -Ls https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz | tar -xvz -C /tmp/
            sudo cp /tmp/ghr_v0.12.0_linux_amd64/ghr /usr/local/bin/

  source-env:
    description: Source environment from the specified file.
    parameters:
      env-file:
        description: An env file to source. The content of this file will be added to $BASH_ENV
        type: string
    steps:
      - run:
          name: Sourcing << parameters.env-file >>
          command: |
            cat "<< parameters.env-file >>" >> $BASH_ENV
            source $BASH_ENV

jobs:
  release-cabal:
    description: Creates a new release using a version from .cabal file
    parameters:
      <<: *common-params
      checkout:
        description: Boolean flag indicating whether to perform checkout or not
        type: boolean
        default: false
      source-env-file:
        description: An env file to source. The content of this file will be added to $BASH_ENV
        type: string
        default: ""
      cabal-file:
        description: Cabal file name (including the .cabal extension)
        type: string
        default: ""
      executor:
        type: executor
        default: default
      attach-workspace:
        description: |
          Boolean for whether or not to attach to an existing workspace.
          This is normally used if you want to upload artefacts produced by another job to the release.
        type: boolean
        default: false
      workspace-root:
        description: |
          Workspace root path that is either an absolute path or a path relative
          to the working directory. Defaults to '.' (the working directory)
        type: string
        default: '.'
    executor: << parameters.executor >>
    steps:
      - when:
          condition: << parameters.checkout >>
          steps: [ checkout ]
      - when:
          condition: << parameters.attach-workspace >>
          steps:
            - attach_workspace:
                at: << parameters.workspace-root >>
      - when:
          name: Sourcing environment
          condition: << parameters.source-env-file >>
          steps:
            - source-env:
                env-file: << parameters.source-env-file >>
      - release-cabal:
          github-token: << parameters.github-token >>
          cabal-file: << parameters.cabal-file >>
          before-release: << parameters.before-release >>
          after-release: << parameters.after-release >>
          artefacts-folder: << parameters.artefacts-folder >>
          draft: << parameters.draft >>
          pre-release: << parameters.pre-release >>

  release:
    parameters:
      <<: *common-params
      checkout:
        description: Boolean flag indicating whether to perform checkout or not
        type: boolean
        default: false
      source-env-file:
        description: An env file to source. The content of this file will be added to $BASH_ENV
        type: string
        default: ""
      tag:
        description: Git tag using as the version number of the release.
        type: string
      title:
        description: Name of the release.
        type: string
      executor:
        type: executor
        default: default
      attach-workspace:
        description: |
          Boolean for whether or not to attach to an existing workspace.
          This is normally used if you want to upload artefacts produced by another job to the release.
        type: boolean
        default: false
      workspace-root:
        description: |
          Workspace root path that is either an absolute path or a path relative
          to the working directory. Defaults to '.' (the working directory)
        type: string
        default: '.'
    executor: << parameters.executor >>
    steps:
      - when:
          condition: << parameters.checkout >>
          steps: [ checkout ]
      - when:
          condition: << parameters.attach-workspace >>
          steps:
            - attach_workspace:
                at: << parameters.workspace-root >>
      - when:
          name: Sourcing environment
          condition: << parameters.source-env-file >>
          steps:
            - source-env:
                env-file: << parameters.source-env-file >>
      - release:
          github-token: << parameters.github-token >>
          tag: << parameters.tag >>
          title: << parameters.title >>
          before-release: << parameters.before-release >>
          after-release: << parameters.after-release >>
          artefacts-folder: << parameters.artefacts-folder >>
          draft: << parameters.draft >>
          pre-release: << parameters.pre-release >>

examples:
  basic-release:
    description: |
      Basic release scenario.
      In this example every push to master will produce a release.
    usage:
      version: 2.1

      orbs:
        github: haskell-works/github-release@1.0.0 # use latest version

      workflow:
        release-my-application:
          jobs:
            - github/release:
                tag: v$CIRCLE_BUILD_NUM
                title: Release v$CIRCLE_BUILD_NUM
                filters:
                  branches:
                    only: master

  release-cabal-version:
    description: |
      Releasing after building an application with haskell-works/haskell-build.
    usage:
      version: 2.1

      orbs:
        haskell: haskell-works/haskell-build@1.0.0 # use latest version
        github: haskell-works/github-release@1.0.0 # use latest version

      workflow:
        jobs:
          - haskell/build:
              name: Build
              write-result-workspace: true

          - github/release-cabal:
              requires: [Build]
              checkout: true
              attach-workspace: true
              artefacts-folder: ./build
              filters:
                branches:
                  only: master


  life-cycle-hooks:
    description: |
      Releasing after building an application with haskell-works/haskell-build.
      This variant does not check out code and uses the workspace produced by the build.
      "before-release" hook is used to prepare artefacts to uploading.
    usage:
      version: 2.1

      orbs:
        haskell: haskell-works/haskell-build@1.0.0 # use latest version
        github: haskell-works/github-release@1.0.0 # use latest version

      workflow:
        - haskell/build:
            name: Build
            write-result-workspace: true

        - github/release:
            requires: [Build]
            attach-workspace: true
            source-env-file: ./build/project.env
            filters:
              branches:
                only: master

            before-release:
              - run:
                  name: Prepare environment for release
                  command: |
                    tar zcvf ./tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz ./build

            artefacts-folder: ./tmp/artefacts
            tag: v${BUILD_EXE_VERSION}
            title: Release v${BUILD_EXE_VERSION}

